import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}

// useEffect(() => {
//     // 1. Fungsi untuk mendapatkan lokasi user
//     const getUserLocation = () => {
//       if (navigator.geolocation) {
//         navigator.geolocation.getCurrentPosition(
//           (position) => {
//             // Jika user mengizinkan, ambil lat & long
//             const { latitude, longitude } = position.coords;
//             fetchWeather(`${latitude},${longitude}`);
//           },
//           (error) => {
//             // Jika user menolak atau error, fallback ke lokasi default (misal: Madrid)
//             console.warn("Akses lokasi ditolak, menggunakan lokasi default.");
//             fetchWeather('Madrid');
//           }
//         );
//       } else {
//         // Browser tidak mendukung Geolocation
//         fetchWeather('Madrid');
//       }
//     };

//     getUserLocation();
//   }, []); // Jalankan sekali saat mount
